utils: analogy: Add missing header file.
This patch fixes the compile error:
analogy_calibrate.h:95:2: error: implicit declaration of function ‘clock_gettime’ [-Werror=implicit-function-declaration]

Signed-off-by: Christoph Muellner <christoph.muellner@theobroma-systems.com>